#! /usr/local/bin/gmake
#  $Id: Makefile 961 2006-11-06 17:38:36Z privmane $

# In order to compile with doubleRep run make like this:  make doubleRep

Libsources= rate4siteOptions.cpp
#Libsources=
LIBNAME = rate4site

# LibCsources= cmdline.c
# LibCsources += getopt.c getopt1.c 

EXEC = rate4site

#rate4site: rate4siteOptions.o
#rate4site.debug: rate4siteOptions.debug.o
#rate4site.doubleRep: rate4siteOptions.doubleRep.o
#rate4site.doubleRep.debug: rate4siteOptions.doubleRep.debug.o



include ../Makefile.generic
